### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by Kkx-b** [taishan1994/BERT-BILSTM-CRF#19]
test_loader=dev_loader,是故意这样设置还是设置错了？
直接改为test_loader=test_loader会影响运行吗？
![ad4e89e991c3d5f8d14104acd4a2c67](https://github.com/taishan1994/BERT-BILSTM-CRF/assets/148549191/d3595f46-4ce7-41f9-b100-9d7a05b39bd0)

**Comment by taishan1994** [comment]
有的数据没有测试集，所以都暂时统一用验证集。
