### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by Kkx-b** [taishan1994/BERT-BILSTM-CRF#20]
作者您好，我在运行main文件时，出现了如图错误，结合gpt解读之后，给出原因(见图2)为缺少参数target_names（说其列表为空），我大致添加修改参数后运行还是报错，麻烦作者指点一下
![12](https://github.com/taishan1994/BERT-BILSTM-CRF/assets/148549191/54498e35-d97e-4bc9-80e1-56f46a1cbaef)
![34](https://github.com/taishan1994/BERT-BILSTM-CRF/assets/148549191/d5b85e2f-10b9-4fc2-b7ab-580ad4b5258d)

**Comment by Kkx-b** [comment]
且我打印输出了true和preds一下，其值均为0
![56](https://github.com/taishan1994/BERT-BILSTM-CRF/assets/148549191/083939b5-ee96-4596-a065-696b0b4ef72f)

**Comment by taishan1994** [comment]
看下target_names是否为空。
